# .github/workflows/app.yaml
name: build
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-20.04
    env:
      OS: ubuntu-20.04
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9

    - name: Install requirements
      run: |
        pip install -r test_requirements
        python setup.py develop

    - name: Start ClickHouse server and client containers
      run: docker-compose -f tests/docker-compose.yml up -d

    - name: Generate Report
      run: |
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
